name: barcode_parser
description: A Flutter package to parse barcodes.
version: 0.0.1
homepage: https://github.com/svprdga/barcode-parser
authors:
  - David Serrano Canales <svprdga>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: